# Generated by Django 2.2.3 on 2020-04-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egypt', '0003_advices'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('puplish', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('-puplish',),
            },
        ),
    ]
