# Generated by Django 2.2.3 on 2020-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('temperature', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('throat', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('chronic', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('respiratory', models.BooleanField(default=False)),
                ('condition', models.BooleanField(default=False)),
                ('visiting', models.BooleanField(default=False)),
                ('worker', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Assure',
                'verbose_name_plural': 'Assures',
                'ordering': ('address',),
            },
        ),
    ]
